model_selection:
  module_0:
    class: RandomForestClassifier
    module: pyspark.ml.classification
    params:
      featuresCol: features
      labelCol: target
      predictionCol:  prediction
    evaluation_module: pyspark.ml.evaluation
    evaluation_class: MulticlassClassificationEvaluator
    evaluationmetric:
      metricName: accuracy
  module_1:
    class: LogisticRegression
    module: pyspark.ml.classification
    params:
      featuresCol: features
      labelCol: target
      predictionCol:  prediction
    evaluation_module: pyspark.ml.evaluation
    evaluation_class: MulticlassClassificationEvaluator
    evaluationmetric:
      metricName: accuracy